### ISSUE TITLE
Copy assets for GitKraken tutorial to this repository

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/assets#10]
Copy the assets used in https://github.com/firstcontributions/first-contributions/blob/master/gui-tool-tutorials/gitkraken-tutorial.md to https://github.com/firstcontributions/assets/tree/master/gui-tool-tutorials/gitkraken-tutorial.

You can find the assets in https://github.com/firstcontributions/first-contributions/tree/master/assets

**Comment by vibalijoshi** [comment]
Can you please elaborate more, this is my first time, so it's difficult to understand what to do

**Comment by Roshanjossey** [comment]
If you go to https://github.com/firstcontributions/first-contributions/blob/master/gui-tool-tutorials/gitkraken-tutorial.md, you'll see that there are some images that we've used in the tutorial.

You can find them in https://github.com/firstcontributions/first-contributions/tree/master/assets.

Copy the assets you see in the tutorial mentioned above the directory https://github.com/firstcontributions/assets/tree/master/gui-tool-tutorials/gitkraken-tutorial in this repository. 

If you didn't understand this, let me know what exactly don't you understand.

**Comment by vibalijoshi** [comment]
That makes it very clear, thanks a lot!

**Comment by vibalijoshi** [comment]
I made a PR, I'm open to feedback as this is my first contribution. Thanks for giving me an opportunity

**Comment by imrahul361** [comment]
Is this issue still available?If yes, I would like to take it @Roshanjossey

**Comment by Roshanjossey** [comment]
@imrahul361, @vibalijoshi has done this in https://github.com/firstcontributions/assets/pull/13.

Closing.
