### ISSUE TITLE
Copy assets for sourcetree tutorial to this repository

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/assets#18]
Copy the assets used in https://github.com/firstcontributions/first-contributions/blob/master/gui-tool-tutorials/sourcetree-macos-tutorial.md to https://github.com/firstcontributions/assets/tree/master/gui-tool-tutorials/sourcetree-macos-tutorial.

You can find the assets in https://github.com/firstcontributions/first-contributions/tree/master/assets

**Comment by venky111** [comment]
Hey I want to take this task

**Comment by ghanender-chauhan** [comment]
please assign me this please!!
