### ISSUE TITLE
Copy assets for sublime merge tutorial to this repository

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/assets#19]
Copy the assets used in https://github.com/firstcontributions/first-contributions/blob/master/gui-tool-tutorials/sublime-merge-tutorial.md to https://github.com/firstcontributions/assets/tree/master/gui-tool-tutorials/sublime-merge-tutorial.

You can find the assets in https://github.com/firstcontributions/first-contributions/tree/master/assets

**Comment by samjones246** [comment]
Happy to take care of this, could I be assigned to it?

**Comment by ghanender-chauhan** [comment]
Assign me this issue

**Comment by sumand4l** [comment]
I'll be grateful to work on this issue?

**Comment by uniyalabhishek** [comment]
@Roshanjossey, added PR #28 for the required changes.
