### ISSUE TITLE
Copy other assets from first-contributions to assets

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/assets#2]
Currently, we have three assets used in https://github.com/firstcontributions/first-contributions/blob/master/README.md in https://github.com/firstcontributions/assets/tree/master/Readme.

Copy the rest of the assets to the same directory.

You can find the assets in https://github.com/firstcontributions/first-contributions/tree/master/assets

**Comment by SPOCTONE** [comment]
pls assign :)

**Comment by Roshanjossey** [comment]
@SPOCTONE, go ahead.

**Comment by SPOCTONE** [comment]
Thanks! that linked issue made things a little bit clearer. working on it ASAP.

**Comment by SPOCTONE** [comment]
Please check if it's correct... or there's anything more that should be done.

**Comment by ghanender-chauhan** [comment]
please assign me this its my first PR
