### ISSUE TITLE
Copy assets for GitHub desktop tutorial to this repository

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/assets#5]
Copy the assets used in https://github.com/firstcontributions/first-contributions/blob/master/gui-tool-tutorials/github-desktop-tutorial.md to https://github.com/firstcontributions/assets/tree/master/gui-tool-tutorials/github-desktop-tutorial.

You can find the assets in https://github.com/firstcontributions/first-contributions/tree/master/assets

**Comment by viswa08** [comment]
Please assign

**Comment by viswa08** [comment]
Please check my PR

**Comment by rahmat-dev** [comment]
Hello sir @Roshanjossey, I have tried to fix the second problem, this my PR https://github.com/firstcontributions/assets/pull/7

**Comment by Roshanjossey** [comment]
Merged and closing
