### ISSUE TITLE
Copy assets for GitHub desktop old version tutorial to this repository

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/assets#8]
Copy the assets used in https://github.com/firstcontributions/first-contributions/blob/master/gui-tool-tutorials/github-desktop-old-version-tutorial.md to https://github.com/firstcontributions/assets/tree/master/gui-tool-tutorials/github-desktop-old-version-tutorial.

You can find the assets in https://github.com/firstcontributions/first-contributions/tree/master/assets

**Comment by imrahul361** [comment]
@Roshanjossey can you assign it to me?

**Comment by Roshanjossey** [comment]
@imrahul361, There is already a pull request for this https://github.com/firstcontributions/assets/pull/12

**Comment by vibalijoshi** [comment]
I made an fully updated pull request #16

**Comment by Roshanjossey** [comment]
#16  is merged. closing
