### ISSUE TITLE
Copy assets for visual studio tutorial to this repository

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/assets#9]
Copy the assets used in https://github.com/firstcontributions/first-contributions/blob/master/gui-tool-tutorials/github-windows-vs2017-tutorial.md to https://github.com/firstcontributions/assets/tree/master/gui-tool-tutorials/github-windows-vs2017-tutorial.

You can find the assets in https://github.com/firstcontributions/first-contributions/tree/master/assets

**Comment by imrahul361** [comment]
@Roshanjossey can i do it?

**Comment by sowmya866** [comment]
Hello,
I did work on this issue,please let me know if there are problems as this is my first xD

**Comment by imrahul361** [comment]
@sowmyaprasaad mam, I ask for it first. U can't just PR an issue without being asked.

**Comment by sowmyaprasaad** [comment]
> @sowmyaprasaad mam, I ask for it first. U can't just PR an issue without being asked.

Hey @imrahul361 
Sorry,I'd seen your same message on all requests on this thread  but was not quite sure which one you decided to work on,so decided to go ahead with this as I had already started working on it.

**Comment by imrahul361** [comment]
I was waiting for issue to be assigned you can't jump directly into any issues randomly you like. You need to ask for it. Before working on it. @sowmyaprasaad

**Comment by sowmya866** [comment]
> I was waiting for issue to be assigned you can't jump directly into any issues randomly you like. You need to ask for it. Before working on it. @sowmyaprasaad

I understand from this comment  that you hadn't started working on the issue yet.
I'm sorry you are upset, but there are 3 other open issues on the same line as this one (which i find you have commented under too) that you can work on as you see fit.
I'm  just here to learn and put in all my energy into meaningful contributions I can make to this community in the long run, and I'm sure you are too :))

**Comment by imrahul361** [comment]
@sowmyaprasaad Contributions doesn't mean you can go and do whatever you like. you need to take permission before working on any repo/issues.
Anybody is learning here. Nobody is born Expert.

**Comment by Roshanjossey** [comment]
Hi @imrahul361, @sowmyaprasaad,

I'm assigning this to both of you. You can both work on this and I'll accept both of your pull requests.

A comment on the discussion above:
You don't have to get permission to work on an issue. You don't have to get the issue assigned to yourself.
It's a good thing to comment that you're working on an issue. This will help others know that there's somebody working on it, so that other multiple people don't work on it which is not productive.
Note that this is not a competition. Work together in the spirit of open source communities. 

Feel free to ask questions if you have any.

**Comment by sowmya866** [comment]
> Hi @imrahul361, @sowmyaprasaad,
> 
> I'm assigning this to both of you. You can both work on this and I'll accept both of your pull requests.
> 
> A comment on the discussion above:
> You don't have to get permission to work on an issue. You don't have to get the issue assigned to yourself.
> It's a good thing to comment that you're working on an issue. This will help others know that there's somebody working on it, so that other multiple people don't work on it which is not productive.
> Note that this is not a competition. Work together in the spirit of open source communities.
> 
> Feel free to ask questions if you have any.

Thank you for your inputs,noted!
